name: veille automatique du mois

on:
  schedule:
    - cron: '5 6 * * *'       # tous les jours pour test rajouter un un apres le 6 pour Tous les 1ers du mois Ã  6:05 UTC
  workflow_dispatch:

jobs:
  veille:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Cloner le dÃ©pÃ´t
        uses: actions/checkout@v4

      - name: ğŸ“¦ Installer Python et les dÃ©pendances
        run: |
          pip install --upgrade pip
          pip install requests beautifulsoup4 pandas jupyter

      - name: âš™ï¸ Convertir le notebook en script Python
        run: |
          jupyter nbconvert --to python veuille.ipynb

      - name: ğŸ“‚ CrÃ©er le dossier veilles si absent
        run: mkdir -p veilles

      - name: ğŸš€ Lancer le script converti
        run: python veuille.py

      - name: ğŸ”„ Ajouter les fichiers gÃ©nÃ©rÃ©s dans Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add veilles/*
          git commit -m "Veille mensuelle automatisÃ©e"
          git push
      
